language: node_js

branches:
  only:
    - master

matrix:
  include:
    - node_js: 6
      os: linux
      script: ./node_modules/.bin/mocha test/basic.js
    - node_js: 8
      os: linux
    - node_js: 10
      os: linux
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - mkdir coverage
      after_script:
        - npm run coverage
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - node_js: 8
      os: windows
      script: npm test
    - node_js: 10
      os: windows
      script: npm test


env:
  global:
    - CC_TEST_REPORTER_ID=e86c6de11dd97ad1777b3212cddc0367b150816025083150839f687b7fbce7f9

before_install:
  - npm config --global set spin false
  # if npm version is less than 5, upgrade to 6
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 5 ]]; then npm i -g npm@6; fi

script:
  - npm run lint:js
  - npm test
